 <?php
 // module/Album/view/album/album/index.phtml:

 $title = 'Testimonials';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <p>
     <a href="<?php echo $this->url('testimonial', array('action'=>'add'));?>">write new testimonial</a>
 </p>

 <table class="table">
 <tr>
     <th>Title</th>
     <th>Artist</th>
     <th>&nbsp;</th>
 </tr>
 <?php foreach ($testimonial as $testimonials) : ?>
 <tr>
     <td><?php echo $this->escapeHtml($testimonial->name);?></td>
     <td><?php echo $this->escapeHtml($testimonial->testimonial);?></td>
 </tr>
 <?php endforeach; ?>
 </table>