 <?php
 // module/Album/view/album/album/index.phtml:

 $title = 'Testimonial';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <p>
     <a href="<?php echo $this->url('home');?>">write new testimonial</a>
 </p>

 <table class="table">
 <tr>
     <th>Name</th>
     <th>Testimonial</th>
 </tr>
 <tr>
     <td><?php echo $this->escapeHtml($testimonial->getName());?></td>
     <td><?php echo $this->escapeHtml($testimonial->getTestimonial());?></td>
 </tr>
 </table>